<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>games.shidogo - <?php if ($title) echo $title; else echo "Go Games, Pattern Search, Joseki Tutor, SGF Editor"; ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<link rel="stylesheet" href="/css/site-style.css?<?=date("Ymd", filectime("css/site-style.css"))?>" type="text/css">

<?php if (strpos(strtolower($_SERVER['HTTP_USER_AGENT']), "iphone") !== false) { ?>
<link rel="stylesheet" href="/css/site-style-iphone.css" type="text/css" media="only screen and (max-device-width: 480px)">
<link rel="stylesheet" href="/player/css/player-iphone.css" type="text/css" media="only screen and (max-device-width: 480px)">
<meta name="viewport" content="width=421, minimum-scale=0.76">
<script type="text/javascript">
eidogoConfig = {skipCss: true};
</script>
<?php } ?>

<?php if (strpos($_SERVER['PHP_SELF'], "/problems") === 0) { ?>
<script type="text/javascript">
eidogoConfig = {enableShortcuts: true};
</script>
<?php } ?>

<script type="text/javascript" src="/min/b=player&amp;g=player_js"></script>
<!--script type="text/javascript" src="/player/js/all.compressed.js?<?=date("Ymd", filectime("player/js/all.compressed.js"))?>"></script-->

<!--script type="text/javascript" src="/player/js/lang.js"></script>
<script type="text/javascript" src="/player/js/eidogo.js"></script>
<script type="text/javascript" src="/player/js/util.js"></script>
<script type="text/javascript" src="/player/i18n/en.js"></script>
<script type="text/javascript" src="/player/js/gametree.js"></script>
<script type="text/javascript" src="/player/js/sgf.js"></script>
<script type="text/javascript" src="/player/js/board.js"></script>
<script type="text/javascript" src="/player/js/rules.js"></script>
<script type="text/javascript" src="/player/js/player.js"></script>
<script type="text/javascript" src="/player/js/init.js"></script-->

</head>
<body>
    
<div id="container">
    
    <div id="header">

        <h1><a href='/'>games.<span>shidogo</span>.com</a></h1>

        <p id="ownership">
            This part of Shidogo is based on EidoGo, and both are <a href="/source">Open Source!</a>
            &nbsp;
        </p>

        <ul id="links">
	    <li style="float:right"><a href="http://www.shidogo.com">Back to Shidogo.com</a></li>
            <li><a href="/upload">Upload</a></li>
            <li><a href="/#blank">Blank Board</a></li>
	    <li><a href="http://www.shidogo.com">Back to Shidogo.com</a></li>
	    <li><a style="color:#770000" href="/help">How to Embed in a Shidogo post</a></li>
        </ul>

    </div>

    <div id="content">
