<?php $title = "Source Code"; include("header.phtml"); ?>

<div id="text-content">

<h2>Embedded SGF Viewer, Shidogo-style</h2>

<p>The Shidogo-style SGF viewer and editor is custom-modified to help you
    express your board situations in any Shidogo question or answer. The Player is derived directly from the Eidogo's player. Both are open source.
</p>

<p>All source code is licensed under the <a href="http://www.fsf.org/licensing/licenses/agpl-3.0.html">AGPLv3</a>.
    In short, this means if you modify the source code, you must allow everyone to see and use those changes
    &mdash; share and share alike!</p>

<p>For help on embedding a player into a Shidogo post, see the <a href="/help">help page</a></p>

<h2>Site Source Code</h2>

<p>The latest, cutting-edge source code for the entire EidoGo site, both client-side and server-side,
    is available from github.com. You can get at it in two ways:</p>

<ol>
	<li><p><a href="http://github.com/jkk/eidogo/tree/master">Browse or download it via the web</a></p></li>
	<li><p>Clone the repository with git:</p>
		<pre><code>git clone git://github.com/jkk/eidogo.git eidogo</pre></code>
</ol>

<p>You can also do the same with games.shidogo's source code:</p>
<ol>
	<li><p><a href="http://github.com/D-Jazz/games.shidogo">Browse or download it via the web</a></p></li>
	<li><p>Clone the repository with git:</p>
	<pre><code>git://github.com/D-Jazz/games.shidogo.git games.shidogo</pre></code>
</ol>

</div>

<?php include("footer.phtml"); ?>
